### ISSUE TITLE
fujiHk

### ISSUE THREAD

**Issue by mlynoza** [unreality/FujiHK#2]
Hello.
Hello, I have a compilation problem.

 I have this error:

C: \ Users \ Dell \ Documents \ Arduino \ fuji-hk \ fuji-hk.ino: In function 'void homeSpanEventHandler (int32_t)':
fuji-hk: 491: 10: error: 'HOMESPAN_WIFI_CONNECTING' was not declared in this scope
     case HOMESPAN_WIFI_CONNECTING:
          ^ ~~~~~~~~~~~~~~~~~~~~~~~
C: \ Users \ Dell \ Documents \ Arduino \ fuji-hk \ fuji-hk.ino: 491: 10: note: suggested alternative: 'LED_WIFI_CONNECTING'
     case HOMESPAN_WIFI_CONNECTING:
          ^ ~~~~~~~~~~~~~~~~~~~~~~~
          LED_WIFI_CONNECTING
fuji-hk: 499: 10: error: 'HOMESPAN_WIFI_CONNECTED' was not declared in this scope
     case HOMESPAN_WIFI_CONNECTED:
          ^ ~~~~~~~~~~~~~~~~~~~~~~
C: \ Users \ Dell \ Documents \ Arduino \ fuji-hk \ fuji-hk.ino: 499: 10: note: suggested alternative: 'LED_WIFI_CONNECTING'
     case HOMESPAN_WIFI_CONNECTED:
          ^ ~~~~~~~~~~~~~~~~~~~~~~

Do you know how to solve the problem?

Maybe you have a compiled version.
Is it possible to share?

greetings
Matthew

**Comment by unreality** [comment]
You can probably fix this by using my fork of Homespan instead of the upstream, and this branch specifically: https://github.com/unreality/Homespan/tree/event-loop

**Comment by unreality** [comment]
@mlynoza a compiled binary is now available, you can flash it to your esp32 with the instructions in the readme
