### ISSUE TITLE
Unable to add accessory, the setup code is incorrect

### ISSUE THREAD

**Issue by FOSV** [unreality/FujiHK#3]
Hi, I have configured everything as per your instructions but, I have changed the configuration code and checked that the terminal returns the correct code I entered. 
When I try to do the procedure to add the accessory, both iPhone and iPad (iOS 16 and iOS 15.7 respectively) return the error "Unable to add accessory, the setup code is incorrect" and the terminal tells me "SRP Proof Verification Failed".

Am I doing something wrong? Can you help me out?

**Comment by unreality** [comment]
I'm unsure, ~~it could be because of the fork of Homespan that the project is currently set to use. Since the TV accessory changes have been merged into the Homespan project you could try switching back to that dependency and see if that makes a difference?~~ (this is all incorrect, i was thinking of a different project)

It could be there is a new SRP verification method? I havent looked at this for quite some time, you could still try to use the original homespan repo as a dependency instead, but you'll have to do a few fixes for some LED-related stuff i jammed in there...

**Comment by FOSV** [comment]
Could these warnings during compilation be related to the problem?

![Immagine 2022-09-17 180942](https://user-images.githubusercontent.com/80490825/190897137-d8a8c56b-c41e-4ff7-b538-8b632446ee49.png)

**Comment by FOSV** [comment]
I have tried to do what you say but without success, I do not have enough experience to be able to fix it properly.
Can I ask you please to fix it? 
Because otherwise, as it is not working, there would be no point in keeping the repository up.
I am sure as you are the author of the code you will be able to fix it in a few minutes.
Thanks in advance

**Comment by FOSV** [comment]
I managed to fix the things that were mismatched _in order to get the code to compile and build without errors_,however, the functions 'addEventCallback' and 'fireEventCallback' remain empty of instructions and as a result the LED does not signal states. 
Could you at least tell me where to find the instructions containing these two functions? I went through the code at length without finding any. 

So I was able to pair the device to homekit without any problems, but at the moment **the air-conditioning machine is not receiving the commands**, ~~but I'm pretty sure it may be a matter of configuring the wired remote control already in the system!~~ The machine, however, receives commands from the wired remote controller already installed.
I checked that the dip switches were set correctly and that everything was connected properly

**Comment by unreality** [comment]
Thats great news,

fireEventcallback is here: https://github.com/unreality/HomeSpan/blob/fb6a888d1845ba317a71f378bc4e92c5ce112df2/src/HomeSpan.cpp#L1374

addEventCallback is here: https://github.com/unreality/HomeSpan/blob/fb6a888d1845ba317a71f378bc4e92c5ce112df2/src/HomeSpan.cpp#L1356

**Comment by FOSV** [comment]
I update you by confirming, in spite of myself, that the LED despite corrections does not work.
Furthermore I can only see the device on homekit but I cannot send commands or even receive statuses from HVAC.
Could you please update and verify the code? Thanks in advance!

**Comment by unreality** [comment]
im unlikely to find time to change this to use the main Homespan tree any time soon, feel free to submit a pull if you manage to get yours working though

**Comment by unreality** [comment]
@FOSV ive created a new release, let me know if it fixes your issues
